apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: server.gitstafette.kearos.net.0.0.0-84a6f15
spec:
  refName: server.gitstafette.kearos.net
  releasedAt: "2022-12-27T18:49:57Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/joostvdg/gitstafette/server-bundle@sha256:4c2d6788b44c3704b567488cdcabafe2fe2ef532268c9e70e642f247e1eee7e6
      template:
      - ytt:
          paths:
          - config
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        app:
          additionalProperties: false
          properties:
            grpcPort:
              default: 50051
              type: integer
            httpPort:
              default: 8080
              type: integer
            httpPrefix:
              default: /
              type: string
            repositories:
              default: ""
              type: string
          type: object
        deploy:
          additionalProperties: false
          properties:
            affinity:
              default: null
              nullable: true
            annotations:
              default: null
              nullable: true
            nodeSelector:
              default: null
              nullable: true
            podSecurityContext:
              default: null
              nullable: true
            resources:
              default: null
              nullable: true
            securityContext:
              default: null
              nullable: true
            tolerations:
              default: []
              nullable: true
          type: object
        httpproxy:
          additionalProperties: false
          properties:
            annotations:
              additionalProperties: false
              properties: {}
              type: object
            enabled:
              default: false
              type: boolean
            fqdn:
              default: lemon.fritz.box
              type: string
            grpc:
              additionalProperties: false
              properties:
                prefix:
                  default: /
                  type: string
              type: object
            http:
              additionalProperties: false
              properties:
                prefix:
                  default: /api
                  type: string
                replacement:
                  default: /
                  type: string
              type: object
            ingressClassName:
              default: contour
              type: string
          type: object
        image:
          additionalProperties: false
          properties:
            pullPolicy:
              default: IfNotPresent
              type: string
            pullSecrets:
              default: []
              nullable: true
            repository:
              default: ghcr.io/joostvdg/gitstafette/server
              type: string
            sha:
              default: ""
              type: string
            tag:
              default: 0.1.0-4e4ce45
              type: string
          type: object
        ingress:
          additionalProperties: false
          properties:
            annotations:
              default: null
              nullable: true
            className:
              default: ""
              type: string
            enabled:
              default: false
              type: boolean
            hosts:
              default: []
              nullable: true
            tls:
              default: []
              nullable: true
          type: object
        name:
          default: gitstafette-server
          type: string
        namespace:
          default: default
          type: string
        security:
          additionalProperties: false
          properties:
            certmanager:
              additionalProperties: false
              properties:
                generateCert:
                  default: false
                  type: boolean
                issuer:
                  additionalProperties: false
                  properties:
                    kind:
                      default: ""
                      type: string
                    name:
                      default: ""
                      type: string
                  type: object
              type: object
          type: object
        service:
          additionalProperties: false
          properties:
            port:
              default: 80
              type: integer
            type:
              default: ClusterIP
              type: string
          type: object
      type: object
  version: 0.0.0-84a6f15
