apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: client.gitstafette.kearos.net.0.0.0-426505f
spec:
  refName: client.gitstafette.kearos.net
  releasedAt: "2022-12-19T21:40:00Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/joostvdg/gitstafette/client-bundle@sha256:af084db944fb00721fa62828fbf4f947c097d2664f247d71c7e87cf1593de4d8
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        app:
          additionalProperties: false
          properties:
            repositories:
              default: ""
              type: string
          type: object
        deploy:
          additionalProperties: false
          properties:
            affinity:
              default: null
              nullable: true
            annotations:
              default: null
              nullable: true
            nodeSelector:
              default: null
              nullable: true
            podSecurityContext:
              default: null
              nullable: true
            resources:
              default: null
              nullable: true
            securityContext:
              default: null
              nullable: true
            tolerations:
              default: []
              nullable: true
          type: object
        grpcServer:
          additionalProperties: false
          properties:
            host:
              default: gitstafette-server.gitstafette.svc.cluster.local
              type: string
            insecureFlag:
              default: insecure
              type: string
            port:
              default: 50051
              type: integer
          type: object
        image:
          additionalProperties: false
          properties:
            pullPolicy:
              default: IfNotPresent
              type: string
            pullSecrets:
              default: []
              nullable: true
            repository:
              default: ghcr.io/joostvdg/gitstafette/client
              type: string
            tag:
              default: 0.1.0-bb3c2fd
              type: string
          type: object
        name:
          default: gitstafette-client
          type: string
        namespace:
          default: default
          type: string
      type: object
  version: 0.0.0-426505f
