apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    kctrl.carvel.dev/repository-version: 0.1.0-ef19793
  creationTimestamp: "2023-02-05T19:44:10Z"
  name: carvel.kearos.net
spec:
  fetch:
    imgpkgBundle:
      image: ghcr.io/joostvdg/carvel-repo@sha256:07b45c62739f6c6761b8aa2fe4ac47d38dc4f75a0bb14b3fac62388d61eb71d1
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
