apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    kctrl.carvel.dev/repository-version: 0.0.0-914234d
  creationTimestamp: "2022-12-13T23:01:51Z"
  name: carvel.kearos.net
spec:
  fetch:
    imgpkgBundle:
      image: index.docker.io/caladreas/carvel-repo@sha256:19e27d937edf69f59f2184aefc2342af33fcbaf530ce35334c7a052d7117b3eb
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
