apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: server.gitstafette.kearos.net.0.0.0-018f07c
spec:
  refName: server.gitstafette.kearos.net
  releasedAt: "2022-12-19T20:07:01Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/joostvdg/gitstafette/server-bundle@sha256:48b776f67bb73ca27f875db92e7b7e5b586c40be06fa9d292ed03a14b201997b
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        app:
          additionalProperties: false
          properties:
            grpcPort:
              default: 50051
              type: integer
            httpPort:
              default: 8080
              type: integer
            httpPrefix:
              default: /
              type: string
            repositories:
              default: ""
              type: string
          type: object
        deploy:
          additionalProperties: false
          properties:
            affinity:
              default: null
              nullable: true
            annotations:
              default: null
              nullable: true
            nodeSelector:
              default: null
              nullable: true
            podSecurityContext:
              default: null
              nullable: true
            resources:
              default: null
              nullable: true
            securityContext:
              default: null
              nullable: true
            tolerations:
              default: []
              nullable: true
          type: object
        httpproxy:
          additionalProperties: false
          properties:
            annotations:
              additionalProperties: false
              properties: {}
              type: object
            enabled:
              default: false
              type: boolean
            fqdn:
              default: lemon.fritz.box
              type: string
            grpc:
              additionalProperties: false
              properties:
                prefix:
                  default: /
                  type: string
              type: object
            http:
              additionalProperties: false
              properties:
                prefix:
                  default: /api
                  type: string
                replacement:
                  default: /
                  type: string
              type: object
            ingressClassName:
              default: contour
              type: string
          type: object
        image:
          additionalProperties: false
          properties:
            pullPolicy:
              default: IfNotPresent
              type: string
            pullSecrets:
              default: []
              nullable: true
            repository:
              default: ghcr.io/joostvdg/gitstafette/server
              type: string
            tag:
              default: 0.1.0-6ed49ec
              type: string
          type: object
        ingress:
          additionalProperties: false
          properties:
            annotations:
              default: null
              nullable: true
            className:
              default: ""
              type: string
            enabled:
              default: false
              type: boolean
            hosts:
              default: []
              nullable: true
            tls:
              default: []
              nullable: true
          type: object
        name:
          default: gitstafette-server
          type: string
        namespace:
          default: default
          type: string
        service:
          additionalProperties: false
          properties:
            port:
              default: 80
              type: integer
            type:
              default: ClusterIP
              type: string
          type: object
      type: object
  version: 0.0.0-018f07c
