apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: server.gitstafette.kearos.net
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - config
      export:
      - imgpkgBundle:
          image: ghcr.io/joostvdg/gitstafette/server-bundle
        includePaths:
        - config
        - .imgpkg/
