apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: client.gitstafette.kearos.net.0.0.0-bc04177
spec:
  refName: client.gitstafette.kearos.net
  releasedAt: "2022-12-27T16:38:57Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/joostvdg/gitstafette/client-bundle@sha256:58ad7efabfa81c5fdc71edc97c4b54cbc1f0da59442059a07528674babfdc3fa
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        app:
          additionalProperties: false
          properties:
            repositories:
              default: ""
              type: string
          type: object
        deploy:
          additionalProperties: false
          properties:
            affinity:
              default: null
              nullable: true
            annotations:
              default: null
              nullable: true
            nodeSelector:
              default: null
              nullable: true
            podSecurityContext:
              default: null
              nullable: true
            resources:
              default: null
              nullable: true
            securityContext:
              default: null
              nullable: true
            tolerations:
              default: []
              nullable: true
          type: object
        grpcServer:
          additionalProperties: false
          properties:
            host:
              default: gitstafette-server.gitstafette.svc.cluster.local
              type: string
            insecureFlag:
              default: insecure
              type: string
            port:
              default: 50051
              type: integer
          type: object
        image:
          additionalProperties: false
          properties:
            pullPolicy:
              default: IfNotPresent
              type: string
            pullSecrets:
              default: []
              nullable: true
            repository:
              default: ghcr.io/joostvdg/gitstafette/client
              type: string
            tag:
              default: 0.1.0-4e4ce45
              type: string
          type: object
        name:
          default: gitstafette-client
          type: string
        namespace:
          default: default
          type: string
        security:
          additionalProperties: false
          properties:
            certmanager:
              additionalProperties: false
              properties:
                generateCert:
                  default: false
                  type: boolean
                host:
                  default: gitstafette-client.gitstafette.svc.cluster.local
                  type: string
                issuer:
                  additionalProperties: false
                  properties:
                    kind:
                      default: ""
                      type: string
                    name:
                      default: ""
                      type: string
                  type: object
              type: object
          type: object
      type: object
  version: 0.0.0-bc04177
