apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: client.gitstafette.kearos.net.0.0.0-921054f
spec:
  refName: client.gitstafette.kearos.net
  releasedAt: "2022-12-13T23:00:20Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: index.docker.io/caladreas/gitstafette-client-bundle@sha256:46d1dde55dd9ae5f1db9b5d68438f9dc6688fc933b0aacd14cc3c595582bef19
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        app:
          additionalProperties: false
          properties:
            repositories:
              default: ""
              type: string
          type: object
        deploy:
          additionalProperties: false
          properties:
            affinity:
              default: null
              nullable: true
            annotations:
              default: null
              nullable: true
            nodeSelector:
              default: null
              nullable: true
            podSecurityContext:
              default: null
              nullable: true
            resources:
              default: null
              nullable: true
            securityContext:
              default: null
              nullable: true
            tolerations:
              default: []
              nullable: true
          type: object
        grpcServer:
          additionalProperties: false
          properties:
            host:
              default: gitstafette-server.gitstafette.svc.cluster.local
              type: string
            insecureFlag:
              default: insecure
              type: string
            port:
              default: 50051
              type: integer
          type: object
        image:
          additionalProperties: false
          properties:
            pullPolicy:
              default: IfNotPresent
              type: string
            pullSecrets:
              default: []
              nullable: true
            repository:
              default: caladreas/gitstafette-client
              type: string
            tag:
              default: 0.1.0-6ed49ec
              type: string
          type: object
        name:
          default: gitstafette-client
          type: string
        namespace:
          default: default
          type: string
      type: object
  version: 0.0.0-921054f
