apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: client.gitstafette.kearos.net.0.1.0-fc2b1d6
spec:
  refName: client.gitstafette.kearos.net
  releasedAt: "2023-01-29T17:28:42Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/joostvdg/gitstafette/client-bundle@sha256:90c3fff653bb13032f12244aae6c7f5f7969497da767a91479f4246176ac2990
      template:
      - ytt:
          paths:
          - config
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        app:
          additionalProperties: false
          properties:
            repositories:
              default: ""
              type: string
          type: object
        deploy:
          additionalProperties: false
          properties:
            affinity:
              default: null
              nullable: true
            annotations:
              default: null
              nullable: true
            nodeSelector:
              default: null
              nullable: true
            podSecurityContext:
              default: null
              nullable: true
            resources:
              default: null
              nullable: true
            securityContext:
              default: null
              nullable: true
            tolerations:
              default: []
              nullable: true
          type: object
        grpcServer:
          additionalProperties: false
          properties:
            host:
              default: gitstafette-server.gitstafette.svc.cluster.local
              type: string
            insecureFlag:
              default: insecure
              type: string
            port:
              default: 50051
              type: integer
          type: object
        image:
          additionalProperties: false
          properties:
            pullPolicy:
              default: IfNotPresent
              type: string
            pullSecrets:
              default: []
              nullable: true
            repository:
              default: ghcr.io/joostvdg/gitstafette/client
              type: string
            sha:
              default: ""
              type: string
            tag:
              default: 0.1.0-4de3564
              type: string
          type: object
        name:
          default: gitstafette-client
          type: string
        namespace:
          default: default
          type: string
        relay:
          additionalProperties: false
          properties:
            enabled:
              default: false
              type: boolean
            host:
              default: 127.0.0.1
              type: string
            insecure:
              default: true
              type: boolean
            port:
              default: "50051"
              type: string
            protocol:
              default: http
              type: string
          type: object
        security:
          additionalProperties: false
          properties:
            certmanager:
              additionalProperties: false
              properties:
                generateCert:
                  default: false
                  type: boolean
                host:
                  default: gitstafette-client.gitstafette.svc.cluster.local
                  type: string
                issuer:
                  additionalProperties: false
                  properties:
                    kind:
                      default: ""
                      type: string
                    name:
                      default: ""
                      type: string
                  type: object
              type: object
          type: object
      type: object
  version: 0.1.0-fc2b1d6
