#@data/values-schema

---
name: "gitstafette-client"
namespace: "default"

app:
  repositories: ""
  clientId: "carvel"

grpcServer:
  host: gitstafette-server.gitstafette.svc.cluster.local
  port: 50051
  insecureFlag: insecure
  streamWindow: 180

relay:
  enabled: false
  host: "127.0.0.1"
  port: "50051"
  path: "/"
  healthCheckPath: "/"
  protocol: "http"
  insecure: true

security:
  certmanager:
    generateCert: false
    host: gitstafette-client.gitstafette.svc.cluster.local
    issuer:
      name: ""
      kind: ""

image:
  repository: ghcr.io/joostvdg/gitstafette/client
  pullPolicy: IfNotPresent
  sha: ""
  tag: "0.1.0-8889ec3"
  #@schema/type any=True
  #@schema/nullable
  #@schema/default []
  pullSecrets: []

deploy:
  #@schema/nullable
  #@schema/type any=True
  annotations: null

  #@schema/nullable
  #@schema/type any=True
  resources: null

  #@schema/nullable
  #@schema/type any=True
  nodeSelector: null
  
  #@schema/type any=True
  #@schema/nullable
  #@schema/default []
  tolerations: 
  
  #@schema/nullable
  #@schema/type any=True
  affinity: null
  
  #@schema/nullable
  #@schema/type any=True
  podSecurityContext: null

  #@schema/nullable
  #@schema/type any=True
  securityContext: null

