#@data/values-schema

---
name: "gitstafette-client"
namespace: "default"

app:
  repositories: ""

grpcServer:
  host: gitstafette-server.gitstafette.svc.cluster.local
  port: 50051
  insecureFlag: insecure

security:
  certmanager:
    generateCert: false
    host: gitstafette-client.gitstafette.svc.cluster.local
    issuer:
      name: ""
      kind: ""

image:
  repository: ghcr.io/joostvdg/gitstafette/client
  pullPolicy: IfNotPresent
  sha: ""
  tag: "0.1.0-4e4ce45"
  #@schema/type any=True
  #@schema/nullable
  #@schema/default []
  pullSecrets: []

deploy:
  #@schema/nullable
  #@schema/type any=True
  annotations: null

  #@schema/nullable
  #@schema/type any=True
  resources: null

  #@schema/nullable
  #@schema/type any=True
  nodeSelector: null
  
  #@schema/type any=True
  #@schema/nullable
  #@schema/default []
  tolerations: 
  
  #@schema/nullable
  #@schema/type any=True
  affinity: null
  
  #@schema/nullable
  #@schema/type any=True
  podSecurityContext: null

  #@schema/nullable
  #@schema/type any=True
  securityContext: null

