#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.name
  labels:
    app.kubernetes.io/name: #@ data.values.name
  annotations: #@ data.values.deploy.annotations
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name:  #@ data.values.name
  template:
    metadata:
      annotations: #@ data.values.deploy.annotations
      labels:
        app.kubernetes.io/name:  #@ data.values.name
    spec:
      imagePullSecrets: #@ data.values.image.pullSecrets
      securityContext: #@ data.values.deploy.securityContext
      containers:
        - name: #@ data.values.name
          securityContext: #@ data.values.deploy.securityContext
          image: #@ data.values.image.repository + ":" + data.values.image.tag
          args:
            - "--repo"
            - #@ str(data.values.app.repositories)
            - --server
            - #@ str(data.values.grpcServer.host)
            - "--port"
            - #@ data.values.grpcServer.port
            - #@ data.values.grpcServer.insecureFlag 
          imagePullPolicy: #@ data.values.image.pullPolicy
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          startupProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          resources: #@ data.values.deploy.resources
      nodeSelector: #@ data.values.deploy.nodeSelector
      affinity: #@ data.values.deploy.affinity
      tolerations: #@ data.values.deploy.tolerations
