#@ load("@ytt:data", "data")
#@ load("funcs.lib.yml", "TLSSecretName", "TLSCertName")
#@ load("@ytt:overlay", "overlay")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.name
  labels:
    app.kubernetes.io/name: #@ data.values.name
  annotations: #@ data.values.deploy.annotations
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name:  #@ data.values.name
  template:
    metadata:
      annotations: #@ data.values.deploy.annotations
      labels:
        app.kubernetes.io/name:  #@ data.values.name
    spec:
      imagePullSecrets: #@ data.values.image.pullSecrets
      securityContext: #@ data.values.deploy.securityContext
      containers:
        - name: #@ data.values.name
          securityContext: #@ data.values.deploy.securityContext
          image: #@ data.values.image.repository + ":" + data.values.image.tag
          args:
            - "--repo"
            - #@ str(data.values.app.repositories)
            - --server
            - #@ str(data.values.grpcServer.host)
            - "--port"
            - #@ str(data.values.grpcServer.port)
            - #@ str(data.values.grpcServer.insecureFlag)
          imagePullPolicy: #@ data.values.image.pullPolicy
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          startupProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          resources: #@ data.values.deploy.resources
          #@ if data.values.security.certmanager.generateCert:
          volumeMounts:
            - mountPath: "/etc/tls"
              name: tls
              readOnly: true
          #@ end
      nodeSelector: #@ data.values.deploy.nodeSelector
      affinity: #@ data.values.deploy.affinity
      tolerations: #@ data.values.deploy.tolerations
      #@ if data.values.security.certmanager.generateCert:
      volumes:
        - name: tls
          secret:
            secretName: #@ TLSSecretName(data.values.security.certmanager.host)
      #@ end

---
#@ if data.values.security.certmanager.generateCert:
#@overlay/match by=overlay.and_op(overlay.subset({"kind": "Deployment"}), overlay.subset({"metadata": {"name": data.values.name}}))
---
spec:
  template:
    spec:
      containers:
        #@overlay/match by="name"
        - name: #@ data.values.name
          args:
            #@overlay/append
            - #@ "--secure"
            - #@ "--caFileLocation"
            - #@ "/etc/tls/ca.crt"
            - #@ "--certFileLocation"
            - #@ "/etc/tls/tls.crt"
            - #@ "--certKeyFileLocation"
            - #@ "/etc/tls/tls.key"
#@ end
