#@data/values
---
app:
  repositories: "537845873"

security:
  certmanager:
    generateCert: true
    host: client
    issuer:
      name: "vault-issuer"
      kind: "ClusterIssuer"

image:
  tag: "0.1.0-5f9d9e6"
  pullPolicy: IfNotPresent

grpcServer:
  host: gitstafette-server.gitstafette.svc.cluster.local
  port: 50051
  oauthToken:
    enabled: true
    secretName: "gitstafette-client-gcr-oauth"

deploy:
  resources:
    limits:
      memory: 16Mi
    requests:
      cpu: 250m
      memory: 16Mi
  env:
    - name: GRPC_TRACE
      value: all
    - name: GRPC_VERBOSITY
      value: DEBUG
    - name: GRPC_GO_LOG_VERBOSITY_LEVEL
      value: 2
    - name: GRPC_GO_LOG_SEVERITY_LEVEL
      value: info

relay:
  enabled: true
  host: "jenkins.jenkins.svc.cluster.local"
  path: "/github-webhook/"
  healthCheckPath: "/login"
  port: "8080"
  protocol: "http"
  insecure: true